name: Tests

on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-13, macos-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install gpac and GStreamer
        uses: ./.github/actions/deps
        with:
          for-test: true

      - name: Install plugins
        if: ${{ runner.os == 'Linux' }}
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y gstreamer1.0-plugins-ugly gstreamer1.0-plugins-bad gstreamer1.0-libav

      - name: Build
        shell: bash
        run: |
          cmake -DENABLE_TESTS=ON -DCMAKE_BUILD_TYPE=Debug -B build
          cmake --build build -j

      # Run the tests
      - name: Test
        if: ${{ runner.os == 'Linux' }}
        shell: bash
        env:
          GST_PLUGIN_PATH: ${{ github.workspace }}/build:$HOME/.local/share/gstreamer-1.0/plugins
          GST_DEBUG: 3
        run: ./build/tests/gstgpacplugin_test
